import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderMain from '@/components/HeaderMain'
import Navbar from '@/components/Navbar'

import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'
import Footer from '@/components/Footer'
import MobNavbar from '@/components/MobNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'kembangsetaman',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMain />
        <Navbar />
        <MobNavbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
